name: autofix.ci
on:
  pull_request:
  push:
permissions: {}
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: |
          npm ci
          npx prettier --write .
      - uses: autofix-ci/action@v1
        with:
          commit-message: "Apply Prettier format"
